### ISSUE TITLE
Default Session

### ISSUE THREAD

**Issue by gibranlp** [pedropenna/musfealle#3]
Is there a way  using this Lightdm theme to set a session to enter for example qtile as default?

**Comment by pedropenna** [comment]
Hi, @gibranlp 

I haven't touched this code in years so I don't know, but I suppose you could easily achieve that by forking and adding code in, say, https://github.com/pedropenna/musfealle/blob/master/js/main.js#L56

Something like this should work 
```
var qliteIndexes = lightdm.sessions
             .map((session, index) => session.name == 'qlite' ? index : -1)
             .filter((element) => element >= 0);
selectedSessionIndex = (qliteIndexes.length > 0) ? qliteIndexes[0] : 0;
selectedSession = lightdm.sessions[0];
```

I just wrote this code in this textbox without any unit tests or anything to check the syntax, so it might need some tweaking :D

**Comment by gibranlp** [comment]
Great thanks man!
